# Generated by Django on 2025-12-14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BuildTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(max_length=200)
                ),
                (
                    'osm_file',
                    models.CharField(max_length=300)
                ),
                (
                    'gtfs_ids',
                    models.JSONField()
                ),
                (
                    'status',
                    models.CharField(
                        max_length=20,
                        choices=[
                            ('pending', 'En attente'),
                            ('preparing', 'Préparation des données'),
                            ('building', 'Construction des tuiles'),
                            ('built', 'Tuiles prêtes'),
                            ('serving', 'Serveur Valhalla actif'),
                            ('error', 'Erreur'),
                        ],
                        default='pending',
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now)
                ),
                (
                    'started_at',
                    models.DateTimeField(blank=True, null=True)
                ),
                (
                    'finished_at',
                    models.DateTimeField(blank=True, null=True)
                ),
                (
                    'logs',
                    models.TextField(blank=True, default='')
                ),
                (
                    'output_dir',
                    models.CharField(
                        max_length=500,
                        blank=True,
                        null=True
                    )
                ),
                (
                    'is_ready',
                    models.BooleanField(default=False)
                ),
                (
                    'is_serving',
                    models.BooleanField(default=False)
                ),
                (
                    'serve_port',
                    models.IntegerField(
                        blank=True,
                        null=True
                    )
                ),
            ],
        ),
    ]
